services:
  edgeconnector-aggregator:
    image: softingindustrial/edgeaggregator
    restart: unless-stopped
    ports:
      - 443
      - 8099
      - 4897
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - config_data:/config
      - mqtt_data:/mqtt

volumes:
  config_data:
  mqtt_data:
