version: '3.9'

services:
  le:
    container_name: LE
    image: litmusedge.azurecr.io/litmusedge-std-docker:latest
    ports:
      - target: 443
        published: 8443
        protocol: tcp
    cap_add:
      - NET_ADMIN
    volumes:
      - edge-data:/var
    restart: unless-stopped

volumes:
  edge-data:
